apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./guestbook-ui-deployment.yaml
  - ./guestbook-ui-svc.yaml
configMapGenerator:
- name: guestbook-config
  literals:
  - NUMBER_OF_REPLICAS=1    
